### ISSUE TITLE
Proposal for default value of optional function/subroutine arguments

### ISSUE THREAD

**Issue by nebulaekg** [j3-fortran/fortran_proposals#41] opened 2019-10-23 18:54 UTC
Fortran cannot set default value in function/subroutine definition for optional arguments. This is an apparent inconvenience if there are multiple optional arguments, compared with C/C++. In such case, using if(present()) can become rather cumbersome. I'd hope that future fortran has such functionality.

**Comment by certik** [comment] 2019-10-23 18:57
@nebulaekg thanks for reporting this. Isn't this a duplicate of #22?

**Comment by nebulaekg** [comment] 2019-10-23 19:00
> @nebulaekg thanks for reporting this. Isn't this a duplicate of #22?

Hi Ondrej, Yes I missed it. Sorry about this.

**Comment by certik** [comment] 2019-10-23 19:01
@nebulaekg no worries! Go ahead and upvote #22 or comment there with improvements. I am going to close this one.

**Closed by certik** 2019-10-23 19:01 UTC
Labels: duplicate
