### ISSUE TITLE
Fortran needs an official logo

### ISSUE THREAD

**Issue by jacobwilliams** [j3-fortran/fortran_proposals#47] opened 2019-10-27 14:06 UTC
It should be modern, iconic, and hopefully not that ugly brown color from the original Fortran manual.

Even [C++](https://github.com/isocpp/logos) has a logo now.

**Comment by certik** [comment] 2019-10-27 14:48
Yes! 

One idea could be to convey a combination of old, trusted, robust, fast and modern. Because it's old, but also modern.

**Comment by milancurcic** [comment] 2019-10-27 21:25
I love this. I suggest that the Fortran logo should **not**:

* Be a white lowercase letter `f` on a blue background
* Have an illustration of a punchcard in it

I think this thread could be used to submit mock-ups or even finished designs, and people can vote up their favorites.

**Comment by jacobwilliams** [comment] 2019-10-27 21:37
Nooooo punchcards!!!

**Comment by cmacmackin** [comment] 2019-10-27 21:59
> I love this. I suggest that the Fortran logo should **not**:
> 
>     * Be a white lowercase letter `f` on a blue background
> 
> ...

I'm feeling a bit attacked in my choice of logo/favicon for FORD :laughing:

**Comment by jacobwilliams** [comment] 2019-10-27 22:01
I made this some time ago, but I'm not wild about it.
![fortran2](https://user-images.githubusercontent.com/6483379/67642607-60f97c00-f8db-11e9-975c-102fd48583e9.png)

**Comment by septcolor** [comment] 2019-10-28 13:09
It seems that some services also want to find a Fortran logo, but no widely accepted ones found...

Fortran / official or unofficial logo
https://github.com/exercism/meta/issues/46
Log needed
https://github.com/exercism/fortran/issues/5

Searching for "Fortran logo" gives [these images](https://www.google.com/search?q=fortran+logo&tbm=isch&source=univ&sa=X&ved=2ahUKEwjYioKEgr_lAhWGdd4KHUA2BhUQsAR6BAgFEAE&biw=1223&bih=950).

Searching for "formula translator logo" gives [these ones](https://www.google.com/search?q=formula+translator+logo&tbm=isch&source=univ&sa=X&ved=2ahUKEwifvuXZgr_lAhUN_GEKHYIcCIMQsAR6BAgEEAE&biw=1223&bih=950)

Searching for "formula one logo" gives [these images](https://www.google.com/search?q=formula+one+logo&tbm=isch&source=univ&sa=X&ved=2ahUKEwik38W6gr_lAhXUPXAKHYvTBYoQsAR6BAgGEAE&biw=1223&bih=950) (just for comparison)

**Comment by milancurcic** [comment] 2019-10-28 13:23
What does "official" mean here? Does it mean approved by the committee? Or selected by the community?

For a first stab, a simple and incremental approach could be surprisingly effective:

* Pick a background color (not brown);
* Pick a foreground color (not brown);
* Pick a font style;
* Type "Fortran";

I also like just the initial variant of it (F), like that of @jacobwilliams, but something less brown :smile: 

(caveat: I'm not a designer, and am not known for good design :D)

**Comment by certik** [comment] 2019-10-28 13:30
Ideally it would be first selected by the community and then approved by the committee.

**Comment by septcolor** [comment] 2019-10-28 14:05
Using some online (free) service and typing "Fortran" gives me this kind of image:
![Fortran_logo2](https://user-images.githubusercontent.com/28031019/67684602-d302bb80-f9d6-11e9-8858-fe14ab83afd8.jpeg)
It might be interesting to experiment with such services and gather samples (as a starter).

Another idea might be to use some animal or fictitious animal icon :)

**Comment by cmacmackin** [comment] 2019-10-28 14:18
Just thinking out loud here, but sometimes language and library logos will somehow incorporate a key feature or concept. For example, the [NumPy logo](https://en.wikipedia.org/wiki/NumPy#/media/File:NumPy_logo.svg) (which I can't say I particularly like) has a representation of a multi-dimensional array.

I would consider Fortran's key features to be its speed and its powerful array handling. So perhaps some syntax to indicate array slicing could be incorporated. Say, instead of just an `F` it could be `F(:)` or `F(:,:)`.

**Comment by milancurcic** [comment] 2019-10-28 14:27
> I would consider Fortran's key features to be its speed and its powerful array handling. So perhaps some syntax to indicate array slicing could be incorporated. Say, instead of just an F it could be F(:) or F(:,:).

I'm a strong advocate for Fortran's native parallelism **and** array features, so would F(:)[:] work? :smile:

**Comment by milancurcic** [comment] 2019-10-28 14:31
> Another idea might be to use some animal or fictitious/symbolic icon :)

I like it. Some recent languages (Rust, Go, etc.) have a language mascot, which helps them appear cute, whimsical, playful, and friendly. Seems like a silly thing, but it would help Fortran's long term image IMO.

**Comment by certik** [comment] 2019-10-28 15:04
I am not a big fan of a mascot personally, but I really like the other proposed ideas.

**Comment by rweed** [comment] 2019-10-28 15:16
Given the resistance of the committee and some vocal compiler developers to anything that will "break legacy code", it should contain an image of a punch card or the old Fortran coding forms (AKA green sheets) :>)

**Comment by jacobwilliams** [comment] 2019-10-28 16:12
Possible spirit animals: cheetah or peregrine falcon (two of the fastest animals).

**Comment by FortranFan** [comment] 2019-10-28 18:14
One would think the first step would be to grab a suitable domain, say HTTPS **fortran.org** or some such, similar to that for other languages e.g., [Python](https://www.python.org/), [C++](https://isocpp.org/about) under the auspices of WG5 org itself or a seeded foundation dedicated to Fortran.  The logo can be part of this.

**Comment by milancurcic** [comment] 2019-10-28 18:21
I've owned fortran-lang.org for some time now (unused). Will be happy to transfer it to the org, or continue managing it myself if somebody can contribute a basic, static, good-looking site (I know basic, but not good looking).

I agree that in the long term, a Fortran foundation is the way to go to ensure the language well being, but that's a whole another beast on its own.

**Comment by certik** [comment] 2019-10-28 21:20
@milancurcic good point. Python has a [Python Software Foundation](https://www.python.org/psf/) (PSF), but I actually don't know how the PSF is involved in approving PEPs (the proposals to improve the Python language). It seems the language standard itself might be different from the foundation.

**Comment by milancurcic** [comment] 2019-10-28 21:52
I think the standard (and the committee) should be separate and independent from the hypothetical Fortran Foundation (FF).

FF would seek donations from orgs invested in Fortran, and would fund the hosting of community websites, meetups, and eventually the development open source compilers and libraries.

In the long term, the FF could fund new members to join J3, which I hear is expensive unless not an alternate to an existing member.

I think foundations should act to funnel unallocated funds into useful causes. I don't think FF should make calls about Fortran Standard proposals.

Of course, as I and others mentioned in other issues, once there is a reference implementation with enough many developers to implement and test experimental features, then we could have a cart behind the horse. In this way a FF could contribute to language development, but I see it a long term vision.

**Comment by jacobwilliams** [comment] 2019-10-30 02:54
Some food for thought (made with Logoist):

![fortran-bracket-3low](https://user-images.githubusercontent.com/6483379/67825256-b3cb6300-fa96-11e9-8d6e-ec5ff1910359.png)

I'm still going to make a peregrine falcon one when I get a chance. :)

**Comment by FortranFan** [comment] 2019-10-30 11:50
@jacobwilliams wrote:

> Some food for thought (made with Logoist):
> 
> ![fortran-bracket-3low](https://user-images.githubusercontent.com/6483379/67825256-b3cb6300-fa96-11e9-8d6e-ec5ff1910359.png)
> 
> I'm still going to make a peregrine falcon one when I get a chance. :)

A couple of points for consideration:

1. Fortran array slice notation as in say ```F(:)``` can have considerable adverse impact in code and should be used sparingly after considerable thought.  So its presence in a logo might convey a questionable message
2. There might be value in retaining focus on **For**mula **Tran**slation and perhaps draw inspiration from famous formulae in science and engineering for the Fortran logo? [example](https://owlcation.com/stem/Top-Ten-Beautiful-Physics-Equations)

**Comment by rweed** [comment] 2019-10-30 12:59
How about something that reflects the many things Fortran helped bring to the world. As an old Aerospace Engineer, I would suggest SR71, Apollo/Saturn5, Space Shuttle, F15/F16, etc. You could also find various examples of buildings, dams, bridges etc along with automobiles. Also ballistic missile and attack subroutines which for those familiar with the technology and the challenges posed by the operating enviroment were as big a challenge as going to the moon.

**Comment by certik** [comment] 2019-10-30 16:03
@rweed great idea. It's actually surprisingly hard to find more details how Fortran was used for some of the things you mention. For example for the Saturn 5 rocket, there is this: https://en.wikipedia.org/wiki/Saturn_V_instrument_unit, and no mention of Fortran. The Apollo 11 Guidance Computer sources are on GitHub: https://github.com/chrislgarry/Apollo-11, and they used their own assembly like language. So I don't know if Fortran was used at all. I assume it was at some point.

**Comment by nncarlson** [comment] 2019-10-30 20:30
> Possible spirit animals: cheetah or peregrine falcon (two of the fastest animals).

This reminded me of a short exchange on the lfortan discussion board on the same topic where someone suggested a dragon (some connection to llvm?) Which prompted this tongue-in-cheek response from me: "Or a somewhat similar dinosaur :) as a nod to the popular impression of Fortran, but pick something agile and quick like a velociraptor!"

**Comment by certik** [comment] 2019-10-30 21:49
I guess I am in a conflict of interest here, since I am also searching for a logo for LFortran... I do like the idea of a Velociraptor.

**Comment by rweed** [comment] 2019-10-31 01:21
This talk of spirit animals reminds me of the pictures of animals that grace the covers of O'Reilly books. The two Fortran related books I remember are Unix for Fortran Programmers which featured a wooly mammoth/mastadon and Kerigan's Migrating to Fortran 90 which featured a Canada goose (a migratory bird). like @nncarlson's dinosaur I think the mammoth (or its modern descendents) might unfortunately be a metaphor for the current state of Fortran ie overly large, clumsy but still capable of covering a lot of ground in a hurry once it gets going.  However, since the current "migration" to Fortran 2003/2008/2018 and beyond is happening at glacial pace, I would propose the Monarch butterfly that migrates from Mexico to as far as southern Canada but takes five generations to do it. ie the butterflies that complete the migration are descendents of the ones that started from Mexico. All the other generations perish along the way. I'm afraid that like the Monarchs some of us will be long dead before Fortran completes its current "migration"

**Comment by sblionel** [comment] 2019-11-03 16:19
Digital Visual Fortran had a logo that I liked, and hinted at the range of application types for which Fortran was well suited. 
![DVF](https://user-images.githubusercontent.com/30088263/68088301-d01b2700-fe2b-11e9-86fb-01db38696844.png)

**Comment by klausler** [comment] 2019-11-08 19:20
https://en.wikipedia.org/wiki/Metasequoia_glyptostroboides#/media/File:MetaseqLeaves.jpg

The *Metasequoia* is a beautiful deciduous tree that was believed to have been extinct for at least 1.5E8 years, but is now flourishing again in arboreta and in the wild.  I have one growing in my back yard.

**Comment by urbanjost** [comment] 2020-01-14 15:12
I really like the Digital Fortan one.  I once had a discussion about this and everyone was settling on a checkered flag that looked somewhat like an F. The checkered flag represented arrays and some thought it evoked the word "Formula" as in Formula 1 racing. It was black and white which was easy to reproduce on paper and in low-res. Been looking and have not found it yet. It was waving but not much so it did not loose the "F" appearance.  At the time something like the Digigal Fortran one would have been too "expensive" to be used as a simple icon.  Is the Digital Visual Fortran one I could use on my web page or is it restricted (if anyone knows)?

**Comment by sblionel** [comment] 2020-01-14 15:31
I would not use the DVF logo as it is - I don't know if the photos in the individual blocks were licensed or were "freeware", so if you do decide to reuse it I suggest you recreate it using different photos. As far as I know, DEC never claimed the logo as a trademark and I really doubt HP would care if the general design was reused.

**Comment by urbanjost** [comment] 2020-01-15 03:43
If a were going to pick a mascot how about a phoenix?

**Comment by everythingfunctional** [comment] 2020-01-15 04:36
The Fortran Phoenix does have a nice ring too it, but somehow I was picturing a turtle with an F on it's back.

**Comment by certik** [comment] 2021-07-01 20:38
I think this is now fixed!   @jacobwilliams and @milancurcic have created a Fortran logo:

https://fortran-lang.org/

This might be the first issue that we fixed in this repository.

**Closed by certik** 2021-07-01 20:38 UTC
